# Generated by Django 3.2.1 on 2021-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='info',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contacts',
            field=models.CharField(max_length=200, null=True, verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=200, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=200, null=True, verbose_name='Pareigos'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='info',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(null=True, to='projects.Employee', verbose_name='Employees'),
        ),
    ]
